Some cli parameter help, usage, etc. for waktusolat-cli

diff --git a/waktusolat-cli b/waktusolat-cli
--- a/waktusolat-cli
+++ b/waktusolat-cli
@@ -15,6 +15,115 @@
 #      waktusolat-cli TRG01
 #
 
+# Fail fast.
+# The set command changes script execution options.
+# For example, normally Bash does not care if some command failed, returning a non-zero exit status code. It just happily jumps to the next one.
+set -Eeuo pipefail
+
+# Get the location
+script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)
+
+# Display helpful help
+usageTest() {
+    cat <<EOF
+Usage: $(basename "${BASH_SOURCE[0]}") [-h] [-v] [-f] [-p param_value] -z JAKIMZONECODE arg1 [arg2...]
+
+Script description here.
+
+EOF
+    exit
+}
+
+usage() {
+    cat <<EOF
+Papar waktu solat berdasarkan kod zone kawasan.
+
+Usage: $(basename "${BASH_SOURCE[0]}") [-h] [-v] ZONE
+where  ZONE := { SGR01 | SGR02 | WLY01 | MLK01 | TRG01 }
+
+EOF
+    exit
+}
+
+# Try to clean up
+trap cleanup SIGINT SIGTERM ERR EXIT
+#
+# Think about the trap like of a finally block for the script.
+# At the end of the script – normal, caused by an error or an external signal – the cleanup() function will be executed.
+# This is a place where you can, for example, try to remove all temporary files created by the script.
+# Just remember that the cleanup() can be called not only at the end but as well having
+# the script done any part of the work. Not necessarily all the resources you try to cleanup will exist.
+cleanup() {
+        trap - SIGINT SIGTERM ERR EXIT
+        # script cleanup here
+}
+
+setup_colors() {
+        if [[ -t 2 ]] && [[ -z "${NO_COLOR-}" ]] && [[ "${TERM-}" != "dumb" ]]; then
+                NOFORMAT='\033[0m' RED='\033[0;31m' GREEN='\033[0;32m' ORANGE='\033[0;33m' BLUE='\033[0;34m' PURPLE='\033[0;35m' CYAN='\033[0;36m' YELLOW='\033[1;33m'
+        else
+                NOFORMAT='' RED='' GREEN='' ORANGE='' BLUE='' PURPLE='' CYAN='' YELLOW=''
+        fi
+}
+
+msg() {
+        echo >&2 -e "${1-}"
+}
+
+die() {
+        local msg=$1
+        local code=${2-1} # default exit status 1
+        msg "$msg"
+        exit "$code"
+}
+
+parse_params() {
+  # default values of variables set from params
+  flag=0
+  param=''
+  zone=''
+
+  while :; do
+        case "${1-}" in
+            -h | --help) usage ;;
+            -v | --verbose) set -x ;;
+            --no-color) NO_COLOR=1 ;;
+            -f | --flag) flag=1 ;; # example flag
+            -p | --param) # example named parameter
+                param="${2-}"
+                shift
+                ;;
+            -z | --zone) # Code ZONE Jakim
+                zone="${2-}"
+                shift
+                ;;
+            -?*) die "Unknown option: $1" ;;
+              *) break ;;
+        esac
+        shift
+  done
+
+  args=("$@")
+
+  # check required params and arguments
+  #[[ -z "${param-}" ]] && die "Missing required parameter: param"
+  [[ ${#args[@]} -eq 0 ]] && die "Missing script arguments"
+
+  return 0
+}
+
+parse_params "$@"
+setup_colors
+
+msg "${RED}Read parameters:${NOFORMAT}"
+msg "- flag: ${flag}"
+msg "- param: ${param}"
+msg "- zone: ${zone}"
+msg "- arguments: ${args[*]-}"
+msg "- \$1: ${1}"
+#msg "- \$2: ${2}"
+#msg "- \$3: ${3}"
+
 # source FILE
 . waktusolatlib.sh
 
@@ -23,15 +132,17 @@ FILE2=/tmp/${USER}-wsp2         # one-line result waktu solat formated for xmoba
 FILE3=/tmp/${USER}-wsp1.bak     # backup good source data file
 LOG=/tmp/${USER}-wsp.log        # for logging
 
+zone=$1
+
+ERROR=false
 ONELINE=""
 NAMASOLAT=()
 MASASOLAT=()
+
 KAWASAN=""
 ZON="" #"$1" #"SGR01" # WLY01 MLK01 TRG01
-zone=$1
 BEARING=""
 TITLE=""
-ERROR=false
 HDATE=""
 MDATE=""
 MDATETIME=""
@@ -119,4 +230,4 @@ while : ; do
     log DEBUG "End main loop"
 done
 
-log DEBUG "End waktusolat-putrajaya-hbar"
+log DEBUG "End waktusolat-cli"
